### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [kathrynljackson/mod_0_skills#1]
@kathrynljackson overall, nice work on this. There are some updates that I'd like for you to make before we can consider your assessment a pass:

* [x] Change your class names to be singular and PascalCase
* [x] Change your instance values to be syntactically correct. ie. if it's a string it should be wrapped in quotes.
* [x] Make sure that all of your methods are either updating or changing an attribute. Some of your methods are only pulling the value of an attribute, which is a bit redundant, as we can pull that information directly from the attribute.

**Comment by kathrynljackson** [comment]
I have added your feedback to the four files in the **classes** section of the assessment.
